version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12.6
    steps:
      - checkout
      - run: go test -count=1 -v ./...

workflows:
  version: 2
  build:
    jobs:
      - build
